-- School Database SQL File
DROP DATABASE IF EXISTS school_db;
CREATE DATABASE school_db;
USE school_db;

CREATE TABLE classes (
    class_id INT PRIMARY KEY AUTO_INCREMENT,
    class_name VARCHAR(50),
    section VARCHAR(10)
);


CREATE TABLE teachers (
    teacher_id INT PRIMARY KEY AUTO_INCREMENT,
    teacher_name VARCHAR(100),
    subject VARCHAR(50)
);


CREATE TABLE students (
    student_id INT PRIMARY KEY AUTO_INCREMENT,
    student_name VARCHAR(100),
    gender VARCHAR(10),
    class_id INT,
    FOREIGN KEY (class_id) REFERENCES classes(class_id)
);


CREATE TABLE subjects (
    subject_id INT PRIMARY KEY AUTO_INCREMENT,
    subject_name VARCHAR(50),
    teacher_id INT,
    FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id)
);


CREATE TABLE attendance (
    attendance_id INT PRIMARY KEY AUTO_INCREMENT,
    student_id INT,
    attend_date DATE,
    status VARCHAR(10),
    FOREIGN KEY (student_id) REFERENCES students(student_id)
);

INSERT INTO classes (class_name, section) VALUES ('Grade 1', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 2', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 3', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 4', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 5', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 6', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 7', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 8', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 9', 'A');
INSERT INTO classes (class_name, section) VALUES ('Grade 10', 'A');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 1', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 2', 'History');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 3', 'History');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 4', 'English');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 5', 'Science');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 6', 'Science');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 7', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 8', 'Geography');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 9', 'History');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 10', 'Science');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 11', 'English');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 12', 'History');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 13', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 14', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 15', 'Geography');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 16', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 17', 'History');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 18', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 19', 'Geography');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 20', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 21', 'Geography');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 22', 'English');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 23', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 24', 'Geography');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 25', 'Science');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 26', 'Maths');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 27', 'Geography');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 28', 'Science');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 29', 'Science');
INSERT INTO teachers (teacher_name, subject) VALUES ('Teacher 30', 'Geography');
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 1', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 2', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 3', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 4', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 5', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 6', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 7', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 8', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 9', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 10', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 11', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 12', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 13', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 14', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 15', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 16', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 17', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 18', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 19', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 20', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 21', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 22', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 23', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 24', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 25', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 26', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 27', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 28', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 29', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 30', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 31', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 32', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 33', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 34', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 35', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 36', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 37', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 38', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 39', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 40', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 41', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 42', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 43', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 44', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 45', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 46', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 47', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 48', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 49', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 50', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 51', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 52', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 53', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 54', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 55', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 56', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 57', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 58', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 59', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 60', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 61', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 62', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 63', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 64', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 65', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 66', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 67', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 68', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 69', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 70', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 71', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 72', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 73', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 74', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 75', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 76', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 77', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 78', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 79', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 80', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 81', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 82', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 83', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 84', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 85', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 86', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 87', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 88', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 89', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 90', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 91', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 92', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 93', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 94', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 95', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 96', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 97', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 98', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 99', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 100', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 101', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 102', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 103', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 104', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 105', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 106', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 107', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 108', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 109', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 110', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 111', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 112', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 113', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 114', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 115', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 116', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 117', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 118', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 119', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 120', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 121', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 122', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 123', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 124', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 125', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 126', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 127', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 128', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 129', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 130', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 131', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 132', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 133', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 134', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 135', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 136', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 137', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 138', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 139', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 140', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 141', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 142', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 143', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 144', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 145', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 146', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 147', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 148', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 149', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 150', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 151', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 152', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 153', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 154', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 155', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 156', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 157', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 158', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 159', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 160', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 161', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 162', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 163', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 164', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 165', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 166', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 167', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 168', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 169', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 170', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 171', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 172', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 173', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 174', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 175', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 176', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 177', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 178', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 179', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 180', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 181', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 182', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 183', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 184', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 185', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 186', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 187', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 188', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 189', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 190', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 191', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 192', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 193', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 194', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 195', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 196', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 197', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 198', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 199', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 200', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 201', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 202', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 203', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 204', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 205', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 206', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 207', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 208', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 209', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 210', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 211', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 212', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 213', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 214', 'Female', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 215', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 216', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 217', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 218', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 219', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 220', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 221', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 222', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 223', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 224', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 225', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 226', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 227', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 228', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 229', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 230', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 231', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 232', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 233', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 234', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 235', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 236', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 237', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 238', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 239', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 240', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 241', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 242', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 243', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 244', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 245', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 246', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 247', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 248', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 249', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 250', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 251', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 252', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 253', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 254', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 255', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 256', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 257', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 258', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 259', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 260', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 261', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 262', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 263', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 264', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 265', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 266', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 267', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 268', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 269', 'Female', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 270', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 271', 'Male', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 272', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 273', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 274', 'Male', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 275', 'Male', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 276', 'Male', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 277', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 278', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 279', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 280', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 281', 'Male', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 282', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 283', 'Female', 2);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 284', 'Male', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 285', 'Male', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 286', 'Female', 7);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 287', 'Female', 10);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 288', 'Male', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 289', 'Female', 9);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 290', 'Male', 8);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 291', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 292', 'Female', 5);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 293', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 294', 'Female', 4);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 295', 'Female', 3);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 296', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 297', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 298', 'Female', 6);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 299', 'Male', 1);
INSERT INTO students (student_name, gender, class_id) VALUES ('Student 300', 'Female', 8);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Science', 26);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Maths', 6);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('History', 5);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Science', 4);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('History', 10);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('History', 1);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('English', 21);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Science', 19);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Maths', 15);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Geography', 23);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Maths', 4);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Science', 26);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('History', 19);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('English', 5);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Geography', 9);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Maths', 23);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Science', 8);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Science', 11);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Geography', 28);
INSERT INTO subjects (subject_name, teacher_id) VALUES ('Maths', 25);
INSERT INTO attendance (student_id, attend_date, status) VALUES (69, '2025-01-04', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (292, '2025-02-24', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (211, '2025-01-15', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (37, '2025-01-05', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (208, '2025-02-10', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (249, '2025-01-19', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (17, '2025-02-03', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (190, '2025-01-17', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (189, '2025-01-31', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (274, '2025-01-19', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (217, '2025-01-08', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (290, '2025-02-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (70, '2025-02-14', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (241, '2025-01-24', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (104, '2025-01-22', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (70, '2025-01-08', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (55, '2025-01-21', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (28, '2025-02-05', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (156, '2025-02-04', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (167, '2025-01-02', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (160, '2025-02-24', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (70, '2025-02-07', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (221, '2025-02-21', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (21, '2025-02-25', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (124, '2025-02-16', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (300, '2025-02-27', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (230, '2025-02-06', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (276, '2025-01-12', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (127, '2025-02-07', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (159, '2025-01-15', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (54, '2025-01-04', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (187, '2025-02-24', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (22, '2025-02-25', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (147, '2025-01-25', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (6, '2025-02-13', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (93, '2025-01-03', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (115, '2025-01-14', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (178, '2025-01-21', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (186, '2025-02-20', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (93, '2025-02-15', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (287, '2025-02-13', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (72, '2025-01-14', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (184, '2025-01-17', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (282, '2025-03-02', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (33, '2025-01-07', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (22, '2025-02-24', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (81, '2025-01-05', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (110, '2025-01-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (185, '2025-01-20', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (128, '2025-02-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (43, '2025-02-09', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (40, '2025-01-12', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (35, '2025-01-21', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (185, '2025-02-05', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (183, '2025-02-25', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (75, '2025-02-28', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (195, '2025-02-05', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (292, '2025-01-14', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (128, '2025-01-13', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (37, '2025-01-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (53, '2025-01-06', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (181, '2025-01-25', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (181, '2025-02-24', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (112, '2025-02-12', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (26, '2025-02-09', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (224, '2025-01-08', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (40, '2025-02-28', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (252, '2025-02-28', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (225, '2025-02-13', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (43, '2025-01-24', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (258, '2025-02-02', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (111, '2025-02-27', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (296, '2025-01-22', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (100, '2025-02-28', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (201, '2025-01-08', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (220, '2025-01-10', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (264, '2025-01-15', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (271, '2025-02-13', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (63, '2025-01-04', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (289, '2025-01-11', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (253, '2025-02-02', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (293, '2025-01-29', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (150, '2025-01-12', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (96, '2025-01-29', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (131, '2025-01-18', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (239, '2025-02-28', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (236, '2025-02-21', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (207, '2025-02-03', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (8, '2025-01-07', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (142, '2025-02-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (166, '2025-02-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (248, '2025-02-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (12, '2025-01-10', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (161, '2025-01-27', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (10, '2025-02-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (287, '2025-01-28', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (259, '2025-02-27', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (212, '2025-03-02', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (19, '2025-02-05', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (54, '2025-02-09', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (208, '2025-02-28', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (12, '2025-01-11', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (141, '2025-01-09', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (178, '2025-02-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (47, '2025-02-18', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (162, '2025-01-11', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (200, '2025-02-16', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (75, '2025-01-23', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (181, '2025-02-21', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (166, '2025-01-18', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (168, '2025-02-24', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (42, '2025-02-22', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (282, '2025-02-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (205, '2025-01-04', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (250, '2025-02-08', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (30, '2025-01-09', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (111, '2025-01-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (77, '2025-01-16', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (208, '2025-01-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (28, '2025-01-29', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (274, '2025-01-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (88, '2025-03-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (58, '2025-01-09', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (133, '2025-01-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (141, '2025-01-26', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (164, '2025-01-30', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (300, '2025-02-28', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (291, '2025-01-31', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (54, '2025-01-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (269, '2025-02-13', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (286, '2025-02-08', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (2, '2025-02-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (46, '2025-03-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (242, '2025-02-17', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (229, '2025-01-11', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (295, '2025-02-10', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (237, '2025-01-22', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (127, '2025-01-14', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (122, '2025-02-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (206, '2025-02-11', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (190, '2025-03-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (30, '2025-02-18', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (174, '2025-01-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (52, '2025-02-17', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (256, '2025-02-06', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (175, '2025-01-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (238, '2025-01-21', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (111, '2025-01-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (92, '2025-02-09', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (266, '2025-02-08', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (215, '2025-01-16', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (147, '2025-01-26', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (71, '2025-01-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (227, '2025-01-30', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (192, '2025-02-22', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (5, '2025-01-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (114, '2025-02-07', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (37, '2025-02-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (290, '2025-01-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (35, '2025-02-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (91, '2025-01-13', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (214, '2025-01-12', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (121, '2025-01-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (246, '2025-02-04', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (272, '2025-01-13', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (80, '2025-01-05', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (201, '2025-03-01', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (89, '2025-02-17', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (231, '2025-02-14', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (210, '2025-02-11', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (39, '2025-02-28', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (86, '2025-01-16', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (239, '2025-01-25', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (159, '2025-01-02', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (235, '2025-02-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (58, '2025-01-07', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (8, '2025-02-04', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (86, '2025-01-23', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (96, '2025-01-30', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (234, '2025-01-04', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (206, '2025-01-05', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (279, '2025-01-31', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (59, '2025-01-30', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (223, '2025-02-10', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (45, '2025-02-15', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (153, '2025-02-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (272, '2025-01-19', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (175, '2025-01-10', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (263, '2025-01-08', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (49, '2025-01-14', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (55, '2025-02-11', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (190, '2025-02-12', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (37, '2025-01-11', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (40, '2025-02-03', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (177, '2025-01-28', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (67, '2025-01-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (29, '2025-01-12', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (88, '2025-01-10', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (156, '2025-02-14', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (175, '2025-01-10', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (13, '2025-02-23', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (209, '2025-01-30', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (290, '2025-01-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (241, '2025-02-08', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (94, '2025-03-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (162, '2025-02-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (170, '2025-01-18', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (156, '2025-01-11', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (37, '2025-01-23', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (114, '2025-01-25', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (5, '2025-02-27', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (54, '2025-01-16', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (238, '2025-01-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (153, '2025-01-29', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (129, '2025-01-13', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (21, '2025-02-11', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (219, '2025-03-02', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (87, '2025-01-22', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (247, '2025-01-31', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (29, '2025-02-20', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (284, '2025-02-21', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (86, '2025-02-26', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (51, '2025-01-26', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (24, '2025-02-12', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (207, '2025-02-25', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (300, '2025-02-23', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (69, '2025-02-09', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (279, '2025-02-04', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (113, '2025-01-14', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (244, '2025-01-10', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (88, '2025-03-01', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (242, '2025-01-27', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (182, '2025-01-02', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (89, '2025-01-30', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (131, '2025-01-07', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (236, '2025-01-27', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (202, '2025-02-10', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (202, '2025-02-19', 'Present');
INSERT INTO attendance (student_id, attend_date, status) VALUES (138, '2025-01-23', 'Absent');
INSERT INTO attendance (student_id, attend_date, status) VALUES (164, '2025-01-03', 'Absent');